### ISSUE TITLE
Add tests to validate rules work

### ISSUE THREAD

**Issue by jamietanna** [apisyouwonthate/style-guide#19]
Would we be up for adding tests to our Spectral rules, similar to what we did in ie https://github.com/co-cddo/api-standards-linting/blob/main/spectral-ruleset-govuk-public/test/unsupported-media-type.test.js

This would be useful to give us a bit more control over the rules, allowing us to add them and have confidence it works before pushing it out for enforcement

More context at https://www.jvt.me/posts/2021/12/22/spectral-jest/

**Comment by philsturgeon** [comment]
Here we go! https://github.com/apisyouwonthate/style-guide/pull/21
