### ISSUE TITLE
Spectral error being raised when linting the pet store

### ISSUE THREAD

**Issue by savage-alex** [apisyouwonthate/style-guide#38]
When linting https://petstore.swagger.io/v2/swagger.json I get a spectral exception with the built ruleset when using the VS code extension
![image](https://user-images.githubusercontent.com/25430683/191992845-37b398d1-ace5-45d2-adf9-e41280b2589b.png)

The error in the output
![image](https://user-images.githubusercontent.com/25430683/191993007-9650c96f-d01f-4d3e-b0da-637db4c25f2e.png)

**Comment by philsturgeon** [comment]
https://github.com/stoplightio/spectral/issues/2269

**Comment by philsturgeon** [comment]
Fixed! 24ed566
