### ISSUE TITLE
How can i test a JS/TS ruleset, without publishing to npm ?

### ISSUE THREAD

**Issue by dishatkr** [apisyouwonthate/style-guide#46]
[Newbie in spectral]
I'm trying to built set of rules using JS/TS, followed a similar pattern in this project -> src/ruleset.ts
How can i test  the rules locally on my machine using spectral lint?

If I add the rules in yaml its easy to test using spectral lint, but for javascript ones, the doc says publish to npm. 
Has anyone tried using yalc, publish it locally and test ?

**Comment by philsturgeon** [comment]
Just run `npm test` without publishing to NPM. None of the docs tell you you have to publish to NPM just to see if it works. 

Hopefully this article helps. 

https://apisyouwonthate.com/blog/distribute-spectral-style-guides-with-npm/#publish-your-spectral-style-guide-to-npm
